services:
  - type: web
    name: whatsapp-loyalty-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/serviceAccount.json
    secretFiles:
      - path: /etc/secrets/serviceAccount.json
        fileName: serviceAccount.json
